/**
 * dbf-schema.cjs
 * Definições centralizadas dos campos DBF.
 * Para alterar o tamanho do código de contrato, mude apenas CODE_LEN.
 */

const CODE_LEN = 9  // dígitos do campo CODIGO dos contratos (ex: 000000001)

const CAMPOS = {

  GRUPOS: [
    { name: 'CODIGO',     type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'GRUPO',      type: 'C', length: 2,  decimals: 0 },
    { name: 'SITUACAO',   type: 'C', length: 1,  decimals: 0 },
    { name: 'NOME',       type: 'C', length: 35, decimals: 0 },
    { name: 'NASCTO_',    type: 'D', length: 8,  decimals: 0 },
    { name: 'ESTCIVIL',   type: 'C', length: 2,  decimals: 0 },
    { name: 'CPF',        type: 'C', length: 11, decimals: 0 },
    { name: 'RG',         type: 'C', length: 20, decimals: 0 },
    { name: 'ENDERECO',   type: 'C', length: 50, decimals: 0 },
    { name: 'BAIRRO',     type: 'C', length: 35, decimals: 0 },
    { name: 'CIDADE',     type: 'C', length: 35, decimals: 0 },
    { name: 'UF',         type: 'C', length: 2,  decimals: 0 },
    { name: 'CEP',        type: 'C', length: 8,  decimals: 0 },
    { name: 'NATURAL',    type: 'C', length: 25, decimals: 0 },
    { name: 'RELIG',      type: 'C', length: 40, decimals: 0 },
    { name: 'CONTATO',    type: 'C', length: 25, decimals: 0 },
    { name: 'TELEFONE',   type: 'C', length: 14, decimals: 0 },
    { name: 'TIPCONT',    type: 'C', length: 2,  decimals: 0 },
    { name: 'VLCARNE',    type: 'C', length: 3,  decimals: 0 },
    { name: 'FORMAPGTO',  type: 'C', length: 2,  decimals: 0 },
    { name: 'SEGURO',     type: 'N', length: 2,  decimals: 0 },
    { name: 'ADMISSAO',   type: 'D', length: 8,  decimals: 0 },
    { name: 'TCARENCIA',  type: 'D', length: 8,  decimals: 0 },
    { name: 'SAITXA',     type: 'C', length: 4,  decimals: 0 },
    { name: 'DIAPGTO',    type: 'C', length: 2,  decimals: 0 },
    { name: 'VENDEDOR',   type: 'C', length: 3,  decimals: 0 },
    { name: 'REGIAO',     type: 'C', length: 3,  decimals: 0 },
    { name: 'COBRADOR',   type: 'C', length: 3,  decimals: 0 },
    { name: 'OBS',        type: 'M', length: 10, decimals: 0 },
    { name: 'RENOVAR',    type: 'D', length: 8,  decimals: 0 },
    { name: 'FUNERAIS',   type: 'N', length: 2,  decimals: 0 },
    { name: 'CIRCINIC',   type: 'C', length: 3,  decimals: 0 },
    { name: 'ULTCIRC',    type: 'C', length: 3,  decimals: 0 },
    { name: 'QTCIRCS',    type: 'N', length: 3,  decimals: 0 },
    { name: 'QTCIRCPG',   type: 'N', length: 3,  decimals: 0 },
    { name: 'TITULAR',    type: 'C', length: 3,  decimals: 0 },
    { name: 'PARTICV',    type: 'N', length: 2,  decimals: 0 },
    { name: 'PARTICF',    type: 'N', length: 2,  decimals: 0 },
    { name: 'NRDEPEND',   type: 'N', length: 2,  decimals: 0 },
    { name: 'ULTIMP_',    type: 'D', length: 8,  decimals: 0 },
    { name: 'ENDER_',     type: 'D', length: 8,  decimals: 0 },
    { name: 'ULTEND',     type: 'C', length: 10, decimals: 0 },
    { name: 'EM_',        type: 'D', length: 8,  decimals: 0 },
    { name: 'POR',        type: 'C', length: 10, decimals: 0 },
    { name: 'ATEND1',     type: 'C', length: 15, decimals: 0 },
    { name: 'ATEND2',     type: 'C', length: 15, decimals: 0 },
    { name: 'ULTNRAUX',   type: 'C', length: 3,  decimals: 0 },
    { name: 'ULTDTAUX',   type: 'D', length: 8,  decimals: 0 },
    { name: 'ULTVLAUX',   type: 'N', length: 11, decimals: 2 },
    { name: 'EMAIL',      type: 'C', length: 50, decimals: 0 },
    { name: 'SEGMESREF',  type: 'D', length: 8,  decimals: 0 },
    { name: 'SEGCODCOB',  type: 'C', length: 3,  decimals: 0 },
    { name: 'SEGSERVCOD', type: 'C', length: 3,  decimals: 0 },
    { name: 'NRSORTEIO',  type: 'C', length: 6,  decimals: 0 },
    { name: 'COMPLEM',    type: 'C', length: 35, decimals: 0 },
  ],

  INSCRITS: [
    { name: 'CODIGO',     type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'GRAU',       type: 'C', length: 1,  decimals: 0 },
    { name: 'SEQ',        type: 'N', length: 2,  decimals: 0 },
    { name: 'EHTITULAR',  type: 'C', length: 1,  decimals: 0 },
    { name: 'NOME',       type: 'C', length: 35, decimals: 0 },
    { name: 'NASCTO_',    type: 'D', length: 8,  decimals: 0 },
    { name: 'ESTCIVIL',   type: 'C', length: 2,  decimals: 0 },
    { name: 'INTERDITO',  type: 'C', length: 1,  decimals: 0 },
    { name: 'SEXO',       type: 'C', length: 1,  decimals: 0 },
    { name: 'TCARENCIA',  type: 'D', length: 8,  decimals: 0 },
    { name: 'LANCTO_',    type: 'D', length: 8,  decimals: 0 },
    { name: 'VIVOFALEC',  type: 'C', length: 1,  decimals: 0 },
    { name: 'FALECTO_',   type: 'D', length: 8,  decimals: 0 },
    { name: 'TIPO',       type: 'C', length: 3,  decimals: 0 },
    { name: 'PROCNR',     type: 'C', length: 7,  decimals: 0 },
    { name: 'POR',        type: 'C', length: 10, decimals: 0 },
    { name: 'FLAG_EXCL',  type: 'C', length: 1,  decimals: 0 },
    { name: 'CPF',        type: 'C', length: 15, decimals: 0 },
    { name: 'SEGMESREF',  type: 'D', length: 8,  decimals: 0 },
    { name: 'SEGPERCEN',  type: 'N', length: 6,  decimals: 2 },
    { name: 'SEGCODCOB',  type: 'C', length: 3,  decimals: 0 },
    { name: 'SEGSERVCOD', type: 'C', length: 3,  decimals: 0 },
  ],

  TAXAS: [
    { name: 'CODIGO',    type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'TIPO',      type: 'C', length: 1,  decimals: 0 },
    { name: 'CIRC',      type: 'C', length: 3,  decimals: 0 },
    { name: 'EMISSAO_',  type: 'D', length: 8,  decimals: 0 },
    { name: 'VALOR',     type: 'N', length: 9,  decimals: 2 },
    { name: 'PGTO_',     type: 'D', length: 8,  decimals: 0 },
    { name: 'VALORPG',   type: 'N', length: 9,  decimals: 2 },
    { name: 'COBRADOR',  type: 'C', length: 3,  decimals: 0 },
    { name: 'FORMA',     type: 'C', length: 1,  decimals: 0 },
    { name: 'BAIXA_',    type: 'D', length: 8,  decimals: 0 },
    { name: 'POR',       type: 'C', length: 10, decimals: 0 },
    { name: 'STAT',      type: 'C', length: 1,  decimals: 0 },
    { name: 'FILIAL',    type: 'C', length: 2,  decimals: 0 },
    { name: 'FLAG_EXCL', type: 'C', length: 1,  decimals: 0 },
    { name: 'CEDENTE',   type: 'C', length: 7,  decimals: 0 },
    { name: 'NNUMERO',   type: 'C', length: 20, decimals: 0 },
    { name: 'CODLAN',    type: 'C', length: 20, decimals: 0 },
  ],

  COBRADOR: [
    { name: 'COBRADOR',  type: 'C', length: 3,  decimals: 0 },
    { name: 'FUNCAO',    type: 'C', length: 1,  decimals: 0 },
    { name: 'NOME',      type: 'C', length: 30, decimals: 0 },
    { name: 'ENDERECO',  type: 'C', length: 30, decimals: 0 },
    { name: 'BAIRRO',    type: 'C', length: 20, decimals: 0 },
    { name: 'CIDADE',    type: 'C', length: 25, decimals: 0 },
    { name: 'TELEFONE',  type: 'C', length: 14, decimals: 0 },
    { name: 'CPF',       type: 'C', length: 11, decimals: 0 },
    { name: 'OBS',       type: 'M', length: 10, decimals: 0 },
    { name: 'PERCENT',   type: 'N', length: 5,  decimals: 1 },
    { name: 'SUPERV',    type: 'C', length: 3,  decimals: 0 },
  ],

  REGIAO: [
    { name: 'CODIGO',   type: 'C', length: 3,  decimals: 0 },
    { name: 'REGIAO',   type: 'C', length: 30, decimals: 0 },
    { name: 'COBRADOR', type: 'C', length: 3,  decimals: 0 },
  ],

  ARQGRUP: [
    { name: 'GRUP',      type: 'C', length: 2,        decimals: 0 },
    { name: 'CLASSE',    type: 'C', length: 2,        decimals: 0 },
    { name: 'INICIO',    type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'FINAL',     type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'ACUMPROC',  type: 'N', length: 2,        decimals: 0 },
    { name: 'MAXPROC',   type: 'N', length: 2,        decimals: 0 },
    { name: 'CPADMISS',  type: 'C', length: 1,        decimals: 0 },
    { name: 'PERIODIC',  type: 'N', length: 3,        decimals: 0 },
    { name: 'QTDREMIR',  type: 'N', length: 3,        decimals: 0 },
    { name: 'PORATEND',  type: 'C', length: 1,        decimals: 0 },
    { name: 'ULTCIRC',   type: 'C', length: 3,        decimals: 0 },
    { name: 'EMISSAO_',  type: 'D', length: 8,        decimals: 0 },
    { name: 'PROCPEND',  type: 'N', length: 3,        decimals: 0 },
    { name: 'CONTRAT',   type: 'N', length: 6,        decimals: 0 },
    { name: 'PARTIC',    type: 'N', length: 6,        decimals: 0 },
    { name: 'PROXCIRC',  type: 'C', length: 3,        decimals: 0 },
  ],

  CLASSES: [
    { name: 'CLASSCOD',  type: 'C', length: 2,  decimals: 0 },
    { name: 'DESCRICAO', type: 'C', length: 35, decimals: 0 },
    { name: 'CONTRAT',   type: 'N', length: 6,  decimals: 0 },
    { name: 'PRIOR',     type: 'C', length: 1,  decimals: 0 },
    { name: 'VLJOIA',    type: 'N', length: 11, decimals: 2 },
    { name: 'NRPARC',    type: 'N', length: 2,  decimals: 0 },
    { name: 'PARCGER',   type: 'N', length: 2,  decimals: 0 },
    { name: 'VLMENSAL',  type: 'N', length: 11, decimals: 2 },
    { name: 'VLDEPEND',  type: 'N', length: 11, decimals: 2 },
    { name: 'NRMESVAL',  type: 'N', length: 2,  decimals: 0 },
    { name: 'RENVENC',   type: 'C', length: 1,  decimals: 0 },
    { name: 'RENUSO',    type: 'C', length: 1,  decimals: 0 },
    { name: 'VLTOTAL',   type: 'N', length: 11, decimals: 2 },
    { name: 'MENSAG1',   type: 'C', length: 30, decimals: 0 },
    { name: 'MENSAG2',   type: 'C', length: 30, decimals: 0 },
  ],

  CIRCULAR: [
    { name: 'GRUPO',     type: 'C', length: 2,  decimals: 0 },
    { name: 'CIRC',      type: 'C', length: 3,  decimals: 0 },
    { name: 'PROCPEND',  type: 'N', length: 2,  decimals: 0 },
    { name: 'EMISSAO_',  type: 'D', length: 8,  decimals: 0 },
    { name: 'MESREF',    type: 'C', length: 4,  decimals: 0 },
    { name: 'VALOR',     type: 'N', length: 9,  decimals: 2 },
    { name: 'MENSCIRC',  type: 'C', length: 60, decimals: 0 },
    { name: 'MENSCIRC1', type: 'C', length: 35, decimals: 0 },
    { name: 'MENSCIRC2', type: 'C', length: 35, decimals: 0 },
    { name: 'EMITIDOS',  type: 'N', length: 6,  decimals: 0 },
    { name: 'PAGOS',     type: 'N', length: 6,  decimals: 0 },
    { name: 'CANCELADOS',type: 'N', length: 6,  decimals: 0 },
    { name: 'LANCTO_',   type: 'D', length: 8,  decimals: 0 },
    { name: 'FUNCIONAR', type: 'C', length: 10, decimals: 0 },
    { name: 'IMPRESS_',  type: 'D', length: 8,  decimals: 0 },
  ],

  PAR_ADM: [
    { name: 'PGRUPO',     type: 'C', length: 2,        decimals: 0 },
    { name: 'P_FILIAL',   type: 'C', length: 2,        decimals: 0 },
    { name: 'PCONTRATO',  type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'PGRAU',      type: 'C', length: 1,        decimals: 0 },
    { name: 'PSEQ',       type: 'N', length: 2,        decimals: 0 },
    { name: 'PVERPAG',    type: 'C', length: 1,        decimals: 0 },
    { name: 'PREPLANC',   type: 'C', length: 1,        decimals: 0 },
    { name: 'LASTCODIGO', type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'NRCANC',     type: 'N', length: 6,        decimals: 0 },
    { name: 'NRREINT',    type: 'N', length: 6,        decimals: 0 },
    { name: 'CONTAREC',   type: 'C', length: 5,        decimals: 0 },
    { name: 'CONTAPAG',   type: 'C', length: 5,        decimals: 0 },
    { name: 'HISTRCFCC',  type: 'C', length: 3,        decimals: 0 },
    { name: 'HISTRCREC',  type: 'C', length: 3,        decimals: 0 },
    { name: 'HISTRCCAR',  type: 'C', length: 3,        decimals: 0 },
    { name: 'HISTPG',     type: 'C', length: 3,        decimals: 0 },
    { name: 'NRAUXREC',   type: 'C', length: 8,        decimals: 0 },
    { name: 'MCODIGO',    type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'MTIPO',      type: 'C', length: 1,        decimals: 0 },
    { name: 'MCIRC',      type: 'C', length: 3,        decimals: 0 },
    { name: 'MGRUPVIP',   type: 'C', length: 2,        decimals: 0 },
    { name: 'COMBARRA',   type: 'C', length: 1,        decimals: 0 },
    { name: 'CINSCR',     type: 'C', length: 1,        decimals: 0 },
    { name: 'COMFALEC',   type: 'C', length: 1,        decimals: 0 },
    { name: 'MPROC1',     type: 'C', length: 5,        decimals: 0 },
    { name: 'MPROC2',     type: 'C', length: 2,        decimals: 0 },
    { name: 'MPROC3',     type: 'C', length: 2,        decimals: 0 },
    { name: 'IMPNRREC',   type: 'C', length: 5,        decimals: 0 },
    { name: 'PROCIMP',    type: 'C', length: 9,        decimals: 0 },
    { name: 'PVALOR',     type: 'N', length: 9,        decimals: 2 },
    { name: 'PCOB',       type: 'C', length: 3,        decimals: 0 },
    { name: 'MMESREF',    type: 'C', length: 4,        decimals: 0 },
    { name: 'PNUMFCC',    type: 'C', length: 8,        decimals: 0 },
    { name: 'P_CIDADE',   type: 'C', length: 25,       decimals: 0 },
    { name: 'P_RECP',     type: 'C', length: 1,        decimals: 0 },
    { name: 'SETUP1',     type: 'C', length: 40,       decimals: 0 },
    { name: 'CGCSETUP',   type: 'C', length: 14,       decimals: 0 },
    { name: 'SETUP2',     type: 'C', length: 50,       decimals: 0 },
    { name: 'SETUP3',     type: 'C', length: 50,       decimals: 0 },
    { name: 'PCEDENTE',   type: 'C', length: 7,        decimals: 0 },
  ],

  PRADENDO: [
    { name: 'CODIGO',     type: 'C', length: 4,  decimals: 0 },
    { name: 'PRODUTO',    type: 'C', length: 30, decimals: 0 },
    { name: 'UNID',       type: 'C', length: 2,  decimals: 0 },
    { name: 'GRUPO',      type: 'C', length: 10, decimals: 0 },
    { name: 'DEPTO',      type: 'C', length: 10, decimals: 0 },
    { name: 'QD_MIN',     type: 'N', length: 4,  decimals: 0 },
    { name: 'QD_EST',     type: 'N', length: 6,  decimals: 0 },
    { name: 'PRECO_CUS',  type: 'N', length: 12, decimals: 2 },
    { name: 'PRECO_VEN',  type: 'N', length: 12, decimals: 2 },
    { name: 'VENDA_',     type: 'D', length: 8,  decimals: 0 },
    { name: 'DT_ULT_ATU', type: 'D', length: 8,  decimals: 0 },
  ],

  ADENDOS: [
    { name: 'CODIGO',     type: 'C', length: CODE_LEN, decimals: 0 },
    { name: 'CODPRODUTO', type: 'C', length: 4,        decimals: 0 },
    { name: 'INCLUIDO_',  type: 'D', length: 8,        decimals: 0 },
    { name: 'IDXD',       type: 'C', length: 20,       decimals: 0 },
    { name: 'IDXM',       type: 'C', length: 20,       decimals: 0 },
    { name: 'FLAG_EXCL',  type: 'C', length: 1,        decimals: 0 },
  ],
}

module.exports = { CAMPOS, CODE_LEN }
