-- -----------------------------------------------------------------------------
-- PARTE 10: SERVI€OS E ATENDIMENTOS
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS service_type( 
    service_type_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    route VARCHAR(200),
    industry VARCHAR(50) DEFAULT 'FUNERAL',
    is_billable TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (service_type_id),
    UNIQUE KEY uk_service_type_name (name),
    INDEX idx_service_type_unit (sys_unit_id),
    CONSTRAINT fk_service_type_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS performed_service( 
    performed_service_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED,
    contract_version_id INT UNSIGNED NOT NULL,
    beneficiary_id INT UNSIGNED,
    service_type_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (performed_service_id),
    INDEX idx_performed_service_unit (sys_unit_id),
    INDEX idx_performed_service_version (contract_version_id),
    INDEX idx_performed_service_beneficiary (beneficiary_id),
    INDEX idx_performed_service_type (service_type_id),
    CONSTRAINT fk_performed_service_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_performed_service_contract FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id),
    CONSTRAINT fk_performed_service_benefic FOREIGN KEY (beneficiary_id) REFERENCES beneficiary(beneficiary_id),
    CONSTRAINT fk_performed_service_servtype FOREIGN KEY (service_type_id) REFERENCES service_type(service_type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_funeral ( 
    service_funeral_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    contract_version_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL COMMENT 'Unit where service was performed',
    sys_user_id INT UNSIGNED NOT NULL COMMENT 'User who recorded the service',
    performed_service_id INT UNSIGNED NOT NULL COMMENT 'Link to general service tracking',
    declarant_id INT UNSIGNED,
    deceased_id INT UNSIGNED,
    office_users_id INT UNSIGNED NOT NULL,
    process_number VARCHAR(25) NOT NULL,
    occurr_at DATE NOT NULL,
    category VARCHAR(25) DEFAULT 'PL' NOT NULL,
    kinship VARCHAR(25) NOT NULL,
    death_at DATE,
    death_time CHAR(5),
    death_address_id INT UNSIGNED,
    payment_at DATE,
    burial_date DATE,
    burial_time CHAR(5),
    cemetery VARCHAR(200),
    paid_amount DECIMAL(19,4),
    paid_in_date DATE,
    group_batch_id INT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (service_funeral_id),
    INDEX idx_service_funeral_version (contract_version_id),
    INDEX idx_service_funeral_unit (sys_unit_id),
    INDEX idx_service_funeral_user (sys_user_id),
    INDEX idx_service_funeral_performed (performed_service_id),
    INDEX idx_service_funeral_deceased (deceased_id),
    INDEX idx_service_funeral_declarant (declarant_id),
    INDEX idx_service_funeral_office (office_users_id),
    INDEX idx_service_funeral_group (group_batch_id),
    CONSTRAINT fk_service_funeral_version FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id),
    CONSTRAINT fk_service_funeral_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_service_funeral_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_service_funeral_perfservic FOREIGN KEY (performed_service_id) REFERENCES performed_service(performed_service_id),
    CONSTRAINT fk_service_funeral_declarant FOREIGN KEY (declarant_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_service_funeral_deceased FOREIGN KEY (deceased_id) REFERENCES beneficiary(beneficiary_id),
    CONSTRAINT fk_service_funeral_officer FOREIGN KEY (office_users_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_service_funeral_group FOREIGN KEY (group_batch_id) REFERENCES group_batch(group_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
 COMMENT='Funeral services provided to contract beneficiaries';

ALTER TABLE beneficiary 
    ADD CONSTRAINT fk_beneficiary_funservice FOREIGN KEY (service_funeral_id) REFERENCES service_funeral(service_funeral_id);

CREATE TABLE IF NOT EXISTS death_event (
    death_event_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    group_batch_id INT UNSIGNED NOT NULL,
    beneficiary_id INT UNSIGNED NOT NULL,
    service_funeral_id INT UNSIGNED NOT NULL,
    event_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_for_billing TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (death_event_id),
    INDEX idx_death_event_group (group_batch_id),
    INDEX idx_death_event_beneficiary (beneficiary_id),
    INDEX idx_death_event_service (service_funeral_id),
    INDEX idx_death_event_group_processed (group_batch_id, processed_for_billing),
    CONSTRAINT fk_death_event_group FOREIGN KEY (group_batch_id) REFERENCES group_batch(group_batch_id),
    CONSTRAINT fk_death_event_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiary(beneficiary_id),
    CONSTRAINT fk_death_event_service FOREIGN KEY (service_funeral_id) REFERENCES service_funeral(service_funeral_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS membership_card( 
    membership_card_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    performed_service_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED,
    sys_user_id INT UNSIGNED,
    contract_version_id INT UNSIGNED,
    beneficiary_id INT UNSIGNED,
    card_cod VARCHAR(100) COMMENT 'C¢digo impresso no cart?o',
    vencimento VARCHAR(100) COMMENT 'V lido at‚...',
    observacao TEXT,
    importado_at TIMESTAMP NULL COMMENT 'Data que foi importado',
    exportado_at TIMESTAMP NULL COMMENT 'Data que exportou para impress?o',
    retorno_at TIMESTAMP NULL COMMENT 'Data do recebimento do cart?o impresso',
    entregue_at TIMESTAMP NULL COMMENT 'Data da entrega ao benefici rio',
    valor DECIMAL(19,4) COMMENT 'Valor (quando cobrado)',
    pago_at TIMESTAMP NULL COMMENT 'Data do pagamento',
    numop VARCHAR(10) COMMENT 'N£mero do caixa',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (membership_card_id),
    INDEX idx_membership_card_performed (performed_service_id),
    INDEX idx_membership_card_unit (sys_unit_id),
    INDEX idx_membership_card_user (sys_user_id),
    INDEX idx_membership_card_version (contract_version_id),
    INDEX idx_membership_card_beneficiary (beneficiary_id),
    CONSTRAINT fk_membership_card_service FOREIGN KEY (performed_service_id) REFERENCES performed_service(performed_service_id),
    CONSTRAINT fk_membership_card_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_membership_card_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_membership_card_version FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id),
    CONSTRAINT fk_membership_card_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiary(beneficiary_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS equipament_rental( 
    equipament_rental_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    performed_service_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED,
    sys_user_id INT UNSIGNED,
    contract_version_id INT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (equipament_rental_id),
    INDEX idx_equipament_rental_performed (performed_service_id),
    CONSTRAINT fk_equipament_rental_perfservic FOREIGN KEY (performed_service_id) REFERENCES performed_service(performed_service_id),
    CONSTRAINT fk_equipament_rental_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_equipament_rental_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_equipament_rental_version FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

