-- -----------------------------------------------------------------------------
-- PARTE 6: CLASSES E GRUPOS
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS category(
    category_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    amount_contracts INT,
    is_periodic TINYINT DEFAULT 1 NOT NULL,
    purchase_value DECIMAL(19,4) NOT NULL,
    number_of_parcels INT NOT NULL,
    generated_parcels INT NOT NULL,
    month_value DECIMAL(19,4) NOT NULL,
    depend_value DECIMAL(19,4),
    number_of_month_valid INT,
    is_renewable TINYINT DEFAULT 0,
    is_renewable_used TINYINT DEFAULT 0,
    total_value DECIMAL(19,4),
    message1 VARCHAR(30),
    message2 VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (category_id),
    UNIQUE KEY uk_class_name (name),
    INDEX idx_class_unit (sys_unit_id),
    INDEX idx_class_user (sys_user_id),
    CONSTRAINT fk_class_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_class_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS group_batch(
    group_batch_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    class_id INT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    group_code VARCHAR(5) NOT NULL,
    begin_code VARCHAR(9) NOT NULL,
    final_code VARCHAR(9) NOT NULL,
    is_periodic TINYINT NOT NULL,
    amount_process INT NOT NULL,
    min_proc INT UNSIGNED NOT NULL,
    max_proc INT UNSIGNED NOT NULL,
    compare_admission TINYINT DEFAULT 0 NOT NULL,
    amount_redeem INT NOT NULL,
    by_service TINYINT DEFAULT 1 NOT NULL,
    death_count INT DEFAULT 0,
    current_death_count INT DEFAULT 0,
    death_threshold INT DEFAULT 10 NOT NULL,
    last_billing_number VARCHAR(3) NOT NULL,
    next_billing_number VARCHAR(3) NOT NULL,
    last_issue_date DATE,
    last_death_charge_date TIMESTAMP NULL,
    pending_process INT,
    number_contracts INT,
    number_lifes INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (group_batch_id),
    UNIQUE KEY uk_group_batch_name (name),
    INDEX idx_group_batch_unit (sys_unit_id),
    INDEX idx_group_batch_user (sys_user_id),
    INDEX idx_group_batch_class (class_id),
    CONSTRAINT fk_group_batch_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_group_batch_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_group_batch_class FOREIGN KEY (class_id) REFERENCES category(category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
