-- -----------------------------------------------------------------------------
-- PARTE 5: EMPRESA E PARCEIROS
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS company (
    company_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parent_company_id INT UNSIGNED,
    company_name VARCHAR(100) NOT NULL,
    legal_name VARCHAR(150) NOT NULL,
    tax_id VARCHAR(50) NOT NULL,
    address_id INT UNSIGNED,
    country VARCHAR(50),
    phone VARCHAR(30),
    email VARCHAR(100),
    website VARCHAR(100),
    logo_url VARCHAR(255),
    fiscal_year_start DATE,
    default_currency CHAR(3) NOT NULL DEFAULT 'BRL',
    is_consolidated TINYINT DEFAULT 0,
    is_active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    INDEX idx_company_name (company_name),
    INDEX idx_company_tax_id (tax_id),
    INDEX idx_company_parent (parent_company_id),
    INDEX idx_company_is_active (is_active),
    CONSTRAINT fk_company_parent FOREIGN KEY (parent_company_id) REFERENCES company(company_id),
    CONSTRAINT fk_company_address FOREIGN KEY (address_id) REFERENCES address(address_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_company_access (
    user_company_access_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    can_view TINYINT DEFAULT 1,
    can_edit TINYINT DEFAULT 0,
    can_approve TINYINT DEFAULT 0,
    can_admin TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (user_company_access_id),
    UNIQUE KEY uk_user_company (sys_user_id, company_id),
    INDEX idx_user_access_company (company_id),
    CONSTRAINT fk_user_access_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_user_access_company FOREIGN KEY (company_id) REFERENCES company(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partner_type (
    partner_type_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    type_name VARCHAR(50) NOT NULL,
    description TEXT,
    is_system TINYINT DEFAULT 0,
    active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    UNIQUE KEY uk_partner_type_company (company_id, type_name),
    INDEX idx_partner_type_company (company_id),
    CONSTRAINT fk_partner_type_company FOREIGN KEY (company_id) REFERENCES company(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS account_type (
    account_type_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    type_name VARCHAR(50) NOT NULL,
    nature VARCHAR(20) NOT NULL,
    description TEXT,
    is_system TINYINT DEFAULT 0,
    active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    UNIQUE KEY uk_account_type_company (company_id, type_name),
    INDEX idx_account_type_company (company_id),
    CONSTRAINT fk_account_type_company FOREIGN KEY (company_id) REFERENCES company(company_id),
    CONSTRAINT chk_account_type_nature CHECK (nature IN ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS region (
    region_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20),
    sys_unit_id INT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    INDEX idx_region_unit (sys_unit_id),
    CONSTRAINT fk_region_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS specialty(
    specialty_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(250) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (specialty_id),
    UNIQUE KEY uk_specialty_name (name),
    INDEX idx_specialty_unit (sys_unit_id),
    INDEX idx_specialty_user (sys_user_id),
    CONSTRAINT fk_specialty_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_specialty_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partner (
    partner_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    owner_id INT UNSIGNED NOT NULL,
    partner_code VARCHAR(30) NOT NULL,
    partner_name VARCHAR(100) NOT NULL,
    legal_name VARCHAR(150),
    login VARCHAR(200) NOT NULL,
    email VARCHAR(100) NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    tax_id VARCHAR(30),
    partner_type_id INT UNSIGNED NOT NULL,
    is_customer TINYINT DEFAULT 0,
    is_vendor TINYINT DEFAULT 0,
    is_collector TINYINT DEFAULT 0,
    is_employee TINYINT DEFAULT 0,
    is_accredited TINYINT DEFAULT 0,
    specialty_id INT UNSIGNED,
    advantages TEXT,
    observation TEXT,
    credit_limit DECIMAL(19, 4),
    payment_terms INT,
    billing_address_id INT UNSIGNED,
    shipping_address_id INT UNSIGNED,
    document1_id INT UNSIGNED,
    document2_id INT UNSIGNED,
    phone VARCHAR(30),
    website VARCHAR(100),
    primary_partner_person VARCHAR(100),
    notes TEXT,
    receivable_account_id INT UNSIGNED,
    payable_account_id INT UNSIGNED,
    currency CHAR(3) DEFAULT 'BRL',
    tax_code_id INT UNSIGNED,
    active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    UNIQUE KEY uk_partner_code (company_id, partner_code),
    UNIQUE KEY idx_partner_tax_id_company (company_id, tax_id),
    INDEX idx_partner_company (company_id),
    INDEX idx_partner_unit (sys_unit_id),
    INDEX idx_partner_user (sys_user_id),
    INDEX idx_partner_type (partner_type_id),
    INDEX idx_partner_name (partner_name),
    INDEX idx_partner_specialty (specialty_id),
    CONSTRAINT fk_partner_company FOREIGN KEY (company_id) REFERENCES company(company_id),
    CONSTRAINT fk_partner_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_partner_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_partner_owner FOREIGN KEY (owner_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_partner_type FOREIGN KEY (partner_type_id) REFERENCES partner_type(partner_type_id),
    CONSTRAINT fk_partner_specialty FOREIGN KEY (specialty_id) REFERENCES specialty(specialty_id),
    CONSTRAINT fk_partner_billing_addr FOREIGN KEY (billing_address_id) REFERENCES address(address_id),
    CONSTRAINT fk_partner_shipping_addr FOREIGN KEY (shipping_address_id) REFERENCES address(address_id),
    CONSTRAINT fk_partner_doc1 FOREIGN KEY (document1_id) REFERENCES document(document_id),
    CONSTRAINT fk_partner_doc2 FOREIGN KEY (document2_id) REFERENCES document(document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE partner
    ADD COLUMN is_customer_flag TINYINT GENERATED ALWAYS AS (IF(is_customer = 1, 1, NULL)) VIRTUAL,
    ADD INDEX idx_partner_customer (company_id, is_customer_flag);

ALTER TABLE partner
    ADD COLUMN is_vendor_flag TINYINT GENERATED ALWAYS AS (IF(is_vendor = 1, 1, NULL)) VIRTUAL,
    ADD INDEX idx_partner_vendor (company_id, is_vendor_flag);

CREATE TABLE IF NOT EXISTS partner_bank_account (
    partner_bank_account_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id INT UNSIGNED NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    account_number VARCHAR(50),
    routing_number VARCHAR(50),
    iban VARCHAR(50),
    swift_code VARCHAR(20),
    bank_address TEXT,
    account_holder VARCHAR(100),
    account_type VARCHAR(30),
    is_default TINYINT DEFAULT 0,
    active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    INDEX idx_partner_bank_partner (partner_id),
    CONSTRAINT fk_partner_bank_partner FOREIGN KEY (partner_id) REFERENCES partner(partner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
