-- -----------------------------------------------------------------------------
-- PARTE 12: COBRAN€AS E PAGAMENTOS
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS contract_charge (
    contract_charge_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    contract_version_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    payment_status_id INT UNSIGNED NOT NULL,
    charge_code VARCHAR(100) NOT NULL,
    due_date DATE NOT NULL,
    amount DECIMAL(19,4) NOT NULL,
    payment_date DATE,
    paid_amount DECIMAL(19,4),
    due_month CHAR(2),
    due_year CHAR(4),
    convenio VARCHAR(20),
    payd_month CHAR(2),
    payd_year CHAR(4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    INDEX idx_contract_charge_version (contract_version_id),
    INDEX idx_contract_charge_unit (sys_unit_id),
    INDEX idx_contract_charge_status (payment_status_id),
    INDEX idx_contract_charge_due (due_date),
    CONSTRAINT fk_contract_charge_contract FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id) ON UPDATE CASCADE,
    CONSTRAINT fk_contract_charge_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_contract_charge_payment FOREIGN KEY (payment_status_id) REFERENCES payment_status(payment_status_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS charge( 
    charge_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    group_batch_id INT UNSIGNED NOT NULL,
    charge_number VARCHAR(7) NOT NULL,
    pending_cases_number INT,
    issue_date TIMESTAMP NULL,
    due_date TIMESTAMP NULL,
    month_ref VARCHAR(100),
    amount DECIMAL(19,4),
    message VARCHAR(100),
    message1 VARCHAR(100),
    message2 VARCHAR(100),
    amount_issued INT,
    amount_paid INT,
    canceled INT,
    release_date TIMESTAMP NULL,
    printing_date TIMESTAMP NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (charge_id),
    INDEX idx_charge_unit (sys_unit_id),
    INDEX idx_charge_user (sys_user_id),
    INDEX idx_charge_group (group_batch_id),
    CONSTRAINT fk_charge_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_charge_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_charge_group FOREIGN KEY (group_batch_id) REFERENCES group_batch(group_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prorated_service(
    prorated_service_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    charge_id INT UNSIGNED NOT NULL,
    service_funeral_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (prorated_service_id),
    INDEX idx_prorated_service_charge (charge_id),
    INDEX idx_prorated_service_funeral (service_funeral_id),
    CONSTRAINT fk_prorated_service_id_charge FOREIGN KEY (charge_id) REFERENCES charge(charge_id),
    CONSTRAINT fk_prorated_service_id_servfuner FOREIGN KEY (service_funeral_id) REFERENCES service_funeral(service_funeral_id),
    CONSTRAINT fk_prorated_service_id_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_prorated_service_id_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bank_slip( 
    bank_slip_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    contract_charge_id INT UNSIGNED NOT NULL,
    seq VARCHAR(7) NOT NULL,
    nnumber VARCHAR(50) NOT NULL,
    charge_code VARCHAR(100) NOT NULL,
    status VARCHAR(100),
    send_at TIMESTAMP NULL,
    send_batch CHAR(7),
    response_at TIMESTAMP NULL,
    response_batch CHAR(7),
    response VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (bank_slip_id),
    INDEX idx_bank_slip_unit (sys_unit_id),
    INDEX idx_bank_slip_user (sys_user_id),
    INDEX idx_bank_slip_charge (contract_charge_id),
    CONSTRAINT fk_bank_slip_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_bank_slip_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_bank_slip_charge FOREIGN KEY (contract_charge_id) REFERENCES contract_charge(contract_charge_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ordpgrc( 
    ordpgrc_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    sys_user_name VARCHAR(50),
    order_number VARCHAR(20) NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(19,4) NOT NULL,
    number_receipt INT UNSIGNED,
    closing_date TIMESTAMP NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (ordpgrc_id),
    INDEX idx_ordpgrc_unit (sys_unit_id),
    INDEX idx_ordpgrc_user (sys_user_id),
    CONSTRAINT fk_ordpgrc_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_ordpgrc_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_receipt( 
    payment_receipt_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    subsidiary_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    contract_version_id INT UNSIGNED NOT NULL,
    status CHAR(2),
    billing_number VARCHAR(100),
    val_payment DECIMAL(19,4),
    val_aux DECIMAL(19,4),
    due_date DATE,
    cashier_number CHAR(8),
    method_pay VARCHAR(100),
    obs_pay VARCHAR(200),
    ordpgrc_id INT UNSIGNED NOT NULL,
    payment_status_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (payment_receipt_id),
    INDEX idx_payment_receipt_subsidiary (subsidiary_id),
    INDEX idx_payment_receipt_unit (sys_unit_id),
    INDEX idx_payment_receipt_user (sys_user_id),
    INDEX idx_payment_receipt_version (contract_version_id),
    INDEX idx_payment_receipt_ordpgrc (ordpgrc_id),
    INDEX idx_payment_receipt_status (payment_status_id),
    CONSTRAINT fk_payment_receipt_subsidiary FOREIGN KEY (subsidiary_id) REFERENCES subsidiary(subsidiary_id),
    CONSTRAINT fk_payment_receipt_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_payment_receipt_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_payment_receipt_contract FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id),
    CONSTRAINT fk_payment_receipt_ordpgrc FOREIGN KEY (ordpgrc_id) REFERENCES ordpgrc(ordpgrc_id),
    CONSTRAINT fk_payment_receipt_paystat FOREIGN KEY (payment_status_id) REFERENCES payment_status(payment_status_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS batch_chk( 
    batch_chk_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    subsidiary_id INT UNSIGNED NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    batch_number VARCHAR(10) NOT NULL,
    detail VARCHAR(100) NOT NULL,
    expenses DECIMAL(19,4) NOT NULL,
    discharge_date DATE NOT NULL,
    commiss_bill DECIMAL(5,2) NOT NULL,
    qtd_other DECIMAL(5,2) NOT NULL,
    vl_other DECIMAL(19,4) NOT NULL,
    qtd_bill DECIMAL(5,2) NOT NULL,
    vl_bill DECIMAL(19,4) NOT NULL,
    payment_value DECIMAL(19,4) NOT NULL,
    nrcctopay VARCHAR(7) NOT NULL,
    cashier_number VARCHAR(7) NOT NULL,
    ordpgrc_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (batch_chk_id),
    INDEX idx_batch_chk_subsidiary (subsidiary_id),
    INDEX idx_batch_chk_unit (sys_unit_id),
    INDEX idx_batch_chk_user (sys_user_id),
    INDEX idx_batch_chk_ordpgrc (ordpgrc_id),
    CONSTRAINT fk_batch_chk_subsidiary FOREIGN KEY (subsidiary_id) REFERENCES subsidiary(subsidiary_id),
    CONSTRAINT fk_batch_chk_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_batch_chk_users FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_batch_chk_ordpgrc FOREIGN KEY (ordpgrc_id) REFERENCES ordpgrc(ordpgrc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS batch_detail( 
    batch_detail_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    batch_chk_id INT UNSIGNED NOT NULL,
    contract_charge_id INT UNSIGNED NOT NULL,
    seq_number VARCHAR(5) NOT NULL,
    billing_number VARCHAR(100),
    amount_received DECIMAL(19,4) NOT NULL,
    process_status CHAR(1) NOT NULL,
    payment_status_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (batch_detail_id),
    INDEX idx_batch_detail_batch (batch_chk_id),
    INDEX idx_batch_detail_charge (contract_charge_id),
    INDEX idx_batch_detail_status (payment_status_id),
    CONSTRAINT fk_batch_detail_batch FOREIGN KEY (batch_chk_id) REFERENCES batch_chk(batch_chk_id),
    CONSTRAINT fk_batch_detail_contcharge FOREIGN KEY (contract_charge_id) REFERENCES contract_charge(contract_charge_id),
    CONSTRAINT fk_batch_detail_paymstat FOREIGN KEY (payment_status_id) REFERENCES payment_status(payment_status_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_cycle (
    billing_cycle_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    group_batch_id INT UNSIGNED NOT NULL,
    death_event_count INT NOT NULL,
    charge_date TIMESTAMP NOT NULL,
    amount_per_contract DECIMAL(19,4) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (billing_cycle_id),
    INDEX idx_billing_cycle_group (group_batch_id),
    CONSTRAINT fk_billing_cycle_group FOREIGN KEY (group_batch_id) REFERENCES group_batch(group_batch_id),
    CONSTRAINT fk_billing_cycle_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_billing_cycle_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_billing (
    contract_billing_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    cycle_id INT UNSIGNED NOT NULL,
    contract_version_id INT UNSIGNED NOT NULL,
    charge_id INT UNSIGNED,
    amount DECIMAL(19,4) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (contract_billing_id),
    INDEX idx_contract_billing_cycle (cycle_id),
    INDEX idx_contract_billing_version (contract_version_id),
    INDEX idx_contract_billing_charge (charge_id),
    CONSTRAINT fk_contract_billing_cycle FOREIGN KEY (cycle_id) REFERENCES billing_cycle(billing_cycle_id),
    CONSTRAINT fk_contract_billing_version FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id),
    CONSTRAINT fk_contract_billing_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_contract_billing_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_contract_billing_charge FOREIGN KEY (charge_id) REFERENCES contract_charge(contract_charge_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_plan (
    payment_plan_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    contract_version_id INT UNSIGNED NOT NULL,
    plan_name VARCHAR(100) NOT NULL,
    total_amount DECIMAL(19,4) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (payment_plan_id),
    INDEX idx_payment_plan_version (contract_version_id),
    CONSTRAINT fk_payment_plan_version FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id),
    CONSTRAINT fk_payment_plan_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_payment_plan_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_plan_installment (
    payment_plan_installment_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    plan_id INT UNSIGNED NOT NULL,
    due_date DATE NOT NULL,
    amount DECIMAL(19,4) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    paid_amount DECIMAL(19,4) DEFAULT 0,
    paid_date DATE,
    charge_id INT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (payment_plan_installment_id),
    INDEX idx_installment_plan (plan_id),
    INDEX idx_installment_charge (charge_id),
    CONSTRAINT fk_installment_plan FOREIGN KEY (plan_id) REFERENCES payment_plan(payment_plan_id),
    CONSTRAINT fk_installment_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_installment_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_installment_charge FOREIGN KEY (charge_id) REFERENCES contract_charge(contract_charge_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_transaction (
    payment_transaction_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_unit_id INT UNSIGNED NOT NULL,
    sys_user_id INT UNSIGNED NOT NULL,
    contract_version_id INT UNSIGNED NOT NULL,
    charge_id INT UNSIGNED,
    installment_id INT UNSIGNED,
    amount DECIMAL(19,4) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    reference_number VARCHAR(100),
    status VARCHAR(20) DEFAULT 'COMPLETED',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (payment_transaction_id),
    INDEX idx_transaction_version (contract_version_id),
    INDEX idx_transaction_charge (charge_id),
    INDEX idx_transaction_installment (installment_id),
    CONSTRAINT fk_transaction_version FOREIGN KEY (contract_version_id) REFERENCES contract_version(contract_version_id),
    CONSTRAINT fk_transaction_unit FOREIGN KEY (sys_unit_id) REFERENCES sys_unit(sys_unit_id),
    CONSTRAINT fk_transaction_user FOREIGN KEY (sys_user_id) REFERENCES sys_user(sys_user_id),
    CONSTRAINT fk_transaction_charge FOREIGN KEY (charge_id) REFERENCES contract_charge(contract_charge_id),
    CONSTRAINT fk_transaction_installment FOREIGN KEY (installment_id) REFERENCES payment_plan_installment(payment_plan_installment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

