-- -----------------------------------------------------------------------------
-- PARTE 16: UTILIT?RIOS E LOGS
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cep_cache( 
    cep_cache_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    cep VARCHAR(8),
    street VARCHAR(500),
    city VARCHAR(500),
    neigborhood VARCHAR(500),
    ibge_code VARCHAR(20),
    uf CHAR(2),
    city_id INT UNSIGNED,
    state_id INT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (cep_cache_id),
    INDEX idx_cep_cache_cep (cep),
    INDEX idx_cep_cache_city (city_id),
    INDEX idx_cep_cache_state (state_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS api_error( 
    api_error_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    api_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    severity TEXT,
    error_code VARCHAR(50),
    error_message TEXT NOT NULL,
    error_details TEXT,
    stack_trace TEXT,
    http_method VARCHAR(10),
    endpoint VARCHAR(255) NOT NULL,
    full_url TEXT NOT NULL,
    request_headers TEXT,
    request_body TEXT,
    query_parameters TEXT,
    http_status INT,
    response_body TEXT,
    response_time_ms INT,
    class_name VARCHAR(255),
    method_name VARCHAR(255),
    line_number INT,
    file_name VARCHAR(255),
    sys_user_id INT UNSIGNED,
    user_ip VARCHAR(45),
    user_agent TEXT,
    environment VARCHAR(50),
    name_server VARCHAR(255),
    is_resolved TINYINT DEFAULT 0,
    resolved_at TIMESTAMP NULL,
    resolved_by INT UNSIGNED,
    resolution_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (api_error_id),
    INDEX idx_api_error_user (sys_user_id),
    INDEX idx_api_error_timestamp (api_timestamp),
    INDEX idx_api_error_resolved (is_resolved)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_log( 
    audit_log_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    sys_user_id INT UNSIGNED,
    audit_action VARCHAR(50) NOT NULL,
    name_table VARCHAR(100) NOT NULL,
    record_id INT NOT NULL,
    old_values TEXT,
    new_values TEXT,
    ip_address VARCHAR(45),
    process_name VARCHAR(100),
    process_parameters TEXT,
    process_outcome VARCHAR(50),
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED,
    updated_by INT UNSIGNED,
    deleted_by INT UNSIGNED,
    PRIMARY KEY (audit_log_id),
    INDEX idx_audit_log_user (sys_user_id),
    INDEX idx_audit_log_record (record_id),
    INDEX idx_audit_log_table (name_table),
    INDEX idx_audit_log_action (audit_action),
    INDEX idx_audit_log_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

